In [17]:
import numpy as np
%matplotlib
from pylab import *
pi = np.pi
fft = np.fft.fft
sin = np.sin

Using matplotlib backend: TkAgg


In [29]:
def get5(a):
    return a[110:115]

In [18]:
a = np.arange(0,1,1/44100)
fs = 44.1*1000
framesize = 2048
fb = fs/framesize

In [100]:
fres1 = fb*112
fres2 = fb*112.2
fres3 = fb*112.49
fres4 = fb*112.50

In [123]:
class Ps:
    def __init__(self, freq):
        for i in range(5):
            key = 'c'+str(i)
            data = sin(2*pi*freq*a[2048*i:2048*(i+1)])
            self.__dict__.update({key:data})
            
            key = 'fft'+str(i)
            fft_data = fft(data)
            self.__dict__.update({key: fft_data})  

In [95]:
def get5ang(d):
    ang = []
    for i in range(5):
        key = 'fft'+str(i)
        data = d.__dict__[key][110:115]
        ang.append(np.angle(data))
    return ang

def diff(ang):
    return [np.round(ang[i+1]-ang[i],6) for i in range(len(ang)-1)]

In [144]:
def ana(audioData, spRate=44100, frameSize=2048, ovrSmp=4):    
    stepSize = int(frameSize/ovrSmp)
    freqPerBin = spRate/frameSize
    expct = 2.0*pi*(stepSize/frameSize)
    
    #split the data
    blocks = int(len(audioData)/stepSize)
    dataSet = [audioData[stepSize*n:(stepSize*n+frameSize)] for n in range(blocks)]
    
    for dataBlock in dataSet:
        fftData = fft(dataBlock)
    
    return dataSet

In [106]:
d1 = Ps(fres1)
d2 = Ps(fres2)
d3 = Ps(fres3)
d4 = Ps(fres4)

ag1, ag2, ag3, ag4 = [get5ang(d) for d in (d1, d2, d3, d4)]
dag1, dag2, dag3, dag4 = [diff(d) for d in (ag1, ag2, ag3, ag4)]

In [107]:
dag1

[array([ 0.264265,  0.10664 , -0.      , -0.152388, -0.096925]),
 array([-0.028698, -0.068215, -0.      , -0.11613 , -0.160797]),
 array([-0.284973, -0.145201, -0.      ,  0.105144,  0.015079]),
 array([ 0.484585,  0.358239, -0.      ,  0.15639 ,  0.236547])]

In [108]:
dag2

[array([ 1.2458  ,  1.250757,  1.255662, -5.022669, -5.017864]),
 array([ 1.256   ,  1.256306,  1.256585,  1.256837,  1.257063]),
 array([ 1.268371,  1.263014,  1.257696,  1.252417,  1.247178]),
 array([-5.04493 , -5.036544, -5.028209,  1.263261,  1.271495])]

In [109]:
dag3

[array([ 3.080028,  3.079518,  3.07901 , -3.204683, -3.205189]),
 array([-3.203245, -3.20372 , -3.204193,  3.078521,  3.078052]),
 array([ 3.079834,  3.079401,  3.078971, -3.204642, -3.205066]),
 array([-3.203474, -3.203859, -3.204239,  3.078569,  3.078196])]

In [110]:
dag4

[array([ 3.141593,  3.141593,  3.141593, -3.141593, -3.141593]),
 array([-3.141593, -3.141593, -3.141593,  3.141593,  3.141593]),
 array([ 3.141593,  3.141593,  3.141593, -3.141593, -3.141593]),
 array([-3.141593, -3.141593, -3.141593,  3.141593,  3.141593])]

In [111]:
ag2

[array([-0.93781789, -0.93996718, -0.94206448,  2.19748184,  2.19548548]),
 array([ 0.30798208,  0.31078977,  0.31359766, -2.82518688, -2.82237856]),
 array([ 1.56398206,  1.56709567,  1.57018221, -1.5683503 , -1.56531588]),
 array([ 2.83235325,  2.83010922,  2.82787807, -0.31593282, -0.31813814]),
 array([-2.21257697, -2.20643504, -2.20033111,  0.94732777,  0.9533566 ])]

In [158]:
fFT = fft(xm.raw_data)
rFFT = np.fft.rfft(xm.raw_data)

In [159]:
plot(abs(fFT))

In [160]:
plot(abs(rFFT))

In [161]:
fFT

array([-3995847.00000000      +0.j        ,
       -1454311.87890575-2759031.70592437j,
        2533608.51226792-2994892.30442922j, ...,
        3416570.02025424 -211968.90377112j,
        2533608.51226795+2994892.30442919j,
       -1454311.87890573+2759031.70592439j])

In [162]:
rFFT

array([ -3.99584700e+06 +0.00000000e+00j,
        -1.45431188e+06 -2.75903171e+06j,
         2.53360851e+06 -2.99489230e+06j, ...,
        -4.79607709e+03 +5.75356143e+02j,
        -2.32506451e+03 +3.66406903e+03j,   6.33000000e+02 +0.00000000e+00j])

In [171]:
np.allclose(fFT[0:int(len(fFT)/2)], rFFT[0:-1])

True